version: "3"
services: 
  my-node-app:
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=development
    command: npm run dev