version: "3"

services: 
  my-node-app:
    container_name: my-node-app-container
    image: mqashoo77/my-node-app
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis
      - postgres
  mongo:
    image: mongo
    container_name: my-mongo-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - my-mongo-db:/data/db
  redis:
    container_name: my-redis-container
    image: redis
  nginx:
    image: nginx:stable-alpine
    container_name: my-nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - my-node-app
  postgres:
    image: postgres
    container_name: my-postgres-contianer
    restart: always
    volumes:
      - my-postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example

volumes:
  my-mongo-db:
  my-postgres-db: